services:

  aquila-philia:
    image: ghcr.io/amphorous/aquila:latest
    env_file: .env.philia
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://${OREXIS_LAN_HOST}:8761/eureka/
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=15
      - SPRING_DATA_REDIS_HOST=${OREXIS_LAN_HOST}

  celestia-philia:
    image: ghcr.io/amphorous/celestia:latest
    env_file: .env.philia
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://${OREXIS_LAN_HOST}:8761/eureka/
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=15
      - SPRING_DATA_MONGODB_HOST=${OREXIS_LAN_HOST}
      - SPRING_DATA_NEO4J_URI=bolt://${OREXIS_LAN_HOST}:7687
      - SPRING_DATA_REDIS_HOST=${OREXIS_LAN_HOST}
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=${SPRING_DATA_NEO4J_AUTHENTICATION_PASSWORD}

  translator-philia:
    image: ghcr.io/amphorous/translator:latest
    env_file: .env.philia
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://${OREXIS_LAN_HOST}:8761/eureka/
      - EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS=5
      - EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS=15
      - SPRING_DATA_REDIS_HOST=${OREXIS_LAN_HOST}
      - SCHEDULER_HSR_CHECKFORUPDATE=false
